### ISSUE TITLE
Linux font configuration override execution order unhelpful

### ISSUE THREAD

**Issue by deliciouslytyped** [Gargaj/Bonzomatic#103]
The check at
https://github.com/Gargaj/Bonzomatic/blob/7269a05f451227b3bd12ab2ce6335009ec7bf989/src/main.cpp#L106
takes precedence over a manually specified font, so if your system doesn't have any of the expected font paths - which a case where a manual override would help - you can't do a manual override of the font with the `config.json`.

**Comment by Gargaj** [comment]
Valid; I'll fix it later today.
