### ISSUE TITLE
Audio configuration for Linux

### ISSUE THREAD

**Issue by deliciouslytyped** [Gargaj/Bonzomatic#104]
What is the correct configuration for audio input to work for the FFT on Linux?
I don't see a way to configure the input device.

**Comment by deliciouslytyped** [comment]
My end goal is to loop back my speaker output - my audio configuration does appear to have a monitor device already.

**Comment by PoroCYon** [comment]
Unfortunately, [miniaudio](https://raw.githubusercontent.com/dr-soft/miniaudio/master/miniaudio.h) (the audio library Bonzomatic uses) only looks at the default devices, and there's no environment variable to override it (unlike with, say, SDL).

On ALSA (when *NOT* using PulseAudio), the default is `dsnoop` (or `dsnoop:0` or `dsnoop:0,0`), and if that fails, miniaudio tries to open `hw:0,0`.

On PulseAudio and JACK, it simply uses whatever the default device is the APIs are giving it.

You could try modifying [this](https://github.com/Gargaj/Bonzomatic/blob/master/src/platform_common/FFT.cpp#L46-L65) code if you want it to force-select a certain backend or device.

**Comment by deliciouslytyped** [comment]
I tried poking around there yesterday but I couldn't really find a way to enumerate devices with miniaudio. I tried changing the backends away from NULL but that always failed.

**Comment by Gargaj** [comment]
> I tried poking around there yesterday but I couldn't really find a way to enumerate devices with miniaudio. I tried changing the backends away from NULL but that always failed. I'm also not too great with C++.

Look for `ma_context_get_devices`

**Comment by deliciouslytyped** [comment]
The snippet I used was 
```cpp
    ma_device_info* devinfoarr;
    ma_uint32 devinfocnt;
    ma_context_get_devices(&context, NULL, NULL, &devinfoarr, &devinfocnt);
    printf("devcnt: %i\n");
    for(int i = 0; i < devinfocnt; i++) {
        printf("name:%s\n", (devinfoarr[i]).name);
        }`
```
but `devinfocnt` is zero.

**Comment by Gargaj** [comment]
That's strange, on Windows that returns my correct number of devices.

**Comment by deliciouslytyped** [comment]
I guess there could be any number of reasons this goes wrong. The problem then is I'm not sure how to debug it.

**Comment by Gargaj** [comment]
Did you try other backends? (First parameter of `ma_context_init`)

**Comment by deliciouslytyped** [comment]
```cpp
    ma_backend backends[] = { ma_backend_pulseaudio, ma_backend_alsa };
    ma_result result = ma_context_init( backends, 0, &context_config, &context );
```
 gives `[FFT] Failed to initialize context: -103`

**Comment by deliciouslytyped** [comment]
I tried listing playback devices with the earlier snippet:
```
[FFT] MAL context initialized, backend is 'Null'
devcnt: 0
name:NULL Playback Device
```

**Comment by deliciouslytyped** [comment]
miniaudio uses dlopen so I'll try to check that it's loading the libraries successfully. Setting `LD_DEBUG=all` in the env gives output that suggests it might not be finding `libasound.so` and `libpulse.so`.

**Comment by deliciouslytyped** [comment]
Ok, much better. I have devices now at least. Thanks for your patience.

**Comment by Gargaj** [comment]
Can you go into a bit more detail? I don't want this to be one of those threads where years down the line someone else has the same problem and then the final post is "k fixed" with no indication of what was wrong and how it got fixed :)

**Comment by deliciouslytyped** [comment]
Ah yeah, I usually do that, thanks for the reminder. 
I'm actually working on an updated package for NixOS. We basically have everything in a nonstandard location. I don't remember how dlopen searches for paths (something something `RPATH`?) but after seeing no devices at all, I got suspicious that miniaudio wasn't seeing anything because it failed to load the audio libraries. So I threw `LD_DEBUG=all` at it and looked for mentions of `libasound.so`. I found some and there weren't any log messages about search paths that looked right, so I passed one I knew was correct manually via `LD_PRELOAD`.

Does miniaudio have some kind of "enable debug messages" mode? It would have been nice to see something like a list of loaded / not loaded backends.

**Comment by Gargaj** [comment]
> Does miniaudio have some kind of "enable debug messages" mode? It would have been nice to see something like a list of loaded / not loaded backends.

Yes:
```#define MA_LOG_LEVEL <Level>
  Sets the logging level. Set level to one of the following:
    MA_LOG_LEVEL_VERBOSE
    MA_LOG_LEVEL_INFO
    MA_LOG_LEVEL_WARNING
    MA_LOG_LEVEL_ERROR```

**Comment by deliciouslytyped** [comment]
I put `#define MA_LOG_LEVEL MA_LOG_LEVEL_VERBOSE` at the top of FFT.cpp but it doesn't seem to leave any more messages than before.

**Comment by Gargaj** [comment]
There's not a lot of logging going on in MA; if you feel there's an issue on their side, you could probably head over to https://github.com/dr-soft/miniaudio and see if you can suggest something on their end.

**Comment by deliciouslytyped** [comment]
I think I'll open an issue requesting more logging then. 

By the way, here's an example of the output of my printf: 
```
devinfocnt: 2
name:Discard all samples (playback) or generate zero samples (capture)
name:Default Audio Device (via PulseAudio)
```

**Comment by deliciouslytyped** [comment]
Sweet! I got it to work!
In pavucontrol, after starting Bonzomatic, an entry showed up under the `Recording` tab, and I was able to select `Monuitor of Built-in Audio Analog Stereo` as the input device.

![image](https://user-images.githubusercontent.com/47436522/57195344-a56e1580-6f51-11e9-84b5-c3be9d56be7b.png)

**Comment by mackron** [comment]
I've gone ahead and added some logging to dlopen/dlsym upstream. It's in the dev branch at the moment, but I'll merge it to master soonish.

> Unfortunately, miniaudio (the audio library Bonzomatic uses) only looks at the default devices

This isn't exactly true. This is only on select backends where it's either not possible or not practical. The ALSA and PulseAudio backends have full support for device enumeration and selection.
