### ISSUE TITLE
Where to put config.json - Lack of info in Readme.md

### ISSUE THREAD

**Issue by flure** [Gargaj/Bonzomatic#111]
The documentation lacks information about where to put the `config.json` file.
When on Windows, it's easy to suppose that this file must be in the same directory as bonzomatic executable. but when on Linux or OSX, it's not obvious, especially if bonzomatic has been installed by `make install`, which puts the executable in a directory not writable by the user (`/usr/local/bin` for example).
Please update the `Readme.md` file to tell where to put the config.json file in each case.

**Comment by Gargaj** [comment]
@PoroCYon @alkama

**Comment by alkama** [comment]
On macOS the config file should be placed alongside the Bonzomatic.app, hence it's not a good option to place Bonzomatic.app in the /Application folder.
If you download the build binary for macOS and unzip it somewhere, it all should work in place.

**Comment by flure** [comment]
And on Linux ? :)

**Comment by sacredbanana** [comment]
Heck I just put the config file in my Applications folder. Causes no harm

**Comment by alkama** [comment]
macOS version should not be installed with make install. It's not a command line tool, it's a proper bundled app with resource icon.
I updated compilation instruction in the readme with PR #113

**Comment by flure** [comment]
Well why is this issue closed ?
There's still no information on where to put the config.json on Linux.

**Comment by Gargaj** [comment]
Wasn't meant to close, Github was being overly enthusiastic.

**Comment by PoroCYon** [comment]
On Linux, it's simply in the working directory of the binary. (Unless someone changed that recently, but I don't think that's the case.)

**Comment by Gargaj** [comment]
https://github.com/Gargaj/Bonzomatic/commit/a0cf67b28b7fafb6394727bcdd716c4fcff3ea72 polishes up the doc and adds code to print the current directory on launch.
