### ISSUE TITLE
GetDefaultFontPath couldn't find ANY default fonts!

### ISSUE THREAD

**Issue by kainoladd** [Gargaj/Bonzomatic#112]
When launching, after selecting resolution,... there is this error:
GetDefaultFontPath couldn't find ANY default fonts!

I managed to track the problem, it's because my windows is on the D: disk, I don't have a C:
I did a workaround mounting \\my_pc\d$ as C:

Maybe the default font path could be defined in the config file?

**Comment by Gargaj** [comment]
Should be fixed with the above commit.

**Comment by Gargaj** [comment]
> Maybe the default font path could be defined in the config file?

You can define your own font, just look closer :)

**Comment by sacredbanana** [comment]
Why is Windows not on your C drive??? Lol

**Comment by Gargaj** [comment]
Installation customization on Windows should be honored; compared to all the other craziness we're struggling with on OSX/Unix, this was an easy fix.

**Comment by sacredbanana** [comment]
Yes I agree it should be catered for and I’m glad it was an easy fix. I’ve just never encountered anyone that doesn’t have windows on C drive before unless they dual boot windows with another windows
