### ISSUE TITLE
Not working on macOS 10.15 beta

### ISSUE THREAD

**Issue by psonice** [Gargaj/Bonzomatic#117]
On macOS 10.15 beta 1, bonzomatic opens, the resolution selection window is all fine, but when hitting 'ignition' it goes fullscreen then simply exits. No crash report, so it looks like the app is quitting gracefully. Have tested on both GPUs (I have 1 for each screen), also with windowed mode (the app just quits instantly in this case). 

This might be fixed in macOS by release time, but I figured it'd be good to flag it early.

**Comment by sacredbanana** [comment]
Odd because it worked for me on Catalina when I tried it. In fact that was the first thing I tested

**Comment by sacredbanana** [comment]
MacOS will kill an app if it attempts to use the camera, microphone etc without asking permission from the user. Have you tried building from the source code recently? I improved the permission handling for Mac recently

**Comment by psonice** [comment]
Huh, odd. I'll test more. Yes - first tried the build I had working fine on 10.14, then tried building from latest source, both exit. Will check permissions.

**Comment by kolnogorov** [comment]
So, Catalina was released, and i can confirm that Bonzomatic doesn't work here.

**Comment by alkama** [comment]
Feel free to compile the current head of bonzomatic (only needs xcode and cmake and guide is in the readme) and debug it.
I promise it's a veeeery easy process !
I sadly cannot install Catalina and help you.

*I never install x.y.0 of a major mac upgrade, I learnt through years it's not a good idea and treat x.y.0 as alpha and x.y.1 - 2 as betas.*
*Also, the complete deprecation of 32bits apps (my poor old music plugins, cant wave them goodbye) and the push to notarization is not helping my transition.*

**Comment by hamidnazari** [comment]
I've raised a pull request to address this issue. The problem is that Bonzomatic can't find a default font to use on Catalina, whereas on older versions of OSX and other platforms this works.

A quick workaround is to create a `config.json` and set the font explicitly. Refer to the [README](https://github.com/Gargaj/Bonzomatic#configuration) for instructions.
