### ISSUE TITLE
Unable to get FFT working on windows (GLFW)

### ISSUE THREAD

**Issue by leavittx** [Gargaj/Bonzomatic#130]
I wonder how the FFT texture is supposed to work on windows. 
Had no luck when just playing some music with Spotify, and mic input also doesn't seem to work.
I see "[FFT] MAL context initialized, backend is 'WASAPI'" string in the log. 
[This](https://github.com/CookieCollective/Live-Coding-Sources/blob/120fa37184a32618f7907aca632a3a1fa92264a5/2017-06-22/07-wsmind.glsl) is the shader I've used for testing

**Comment by Gargaj** [comment]
Do you have your stereo out routed into your recording device?

**Comment by Gargaj** [comment]
Also in your shader `texture(texFFT, 0.001).r` is only sampling a single point, which may not get any data.

**Comment by leavittx** [comment]
Great, I got it working when enabling Stereo Mix device! 
Headphones output doesn't seem to work though, and neither I have an idea of how to make it work with external Focusrite audio card. Maybe I should use jack or something.
The shader I've initially used isn't the best indeed, not I have a better one.
