### ISSUE TITLE
Sync Mode for online only events

### ISSUE THREAD

**Issue by GyrosGeier** [Gargaj/Bonzomatic#132]
For a live shader showdown when we can't leave the house, it would be nice to have a sync mode where people can type and test at home, and a second instance replicates the same view over the internet, only synchronizing editing commands and view controls.
Allowing the second instance to decouple view controls and only follow source code updates might also help commentators to explain something.

**Comment by Gargaj** [comment]
That sounds like a very specific request that is better relegated to a fork.

**Comment by alkama** [comment]
This fork is being worked on and @TheNuSan even made a prototype that works great.
So expect this fork to be soon available :D

**Comment by TheNuSan** [comment]
Yes, we had the same idea and started working on it. A first version is already working quite fine, you can get it there [https://github.com/TheNuSan/Bonzomatic/releases](https://github.com/TheNuSan/Bonzomatic/releases)

**Comment by alkama** [comment]
NuSan's release contains a windows server. Alternatively I made one in Go that can be compiled for any target or deployed using Docker and/or Docker-Compose:
https://github.com/alkama/BonzomaticServer
