### ISSUE TITLE
[ubuntu] alsa sound dependency

### ISSUE THREAD

**Issue by ivan-cx** [Gargaj/Bonzomatic#134]
Hello and thank you for this amazing tool!

Found a minor issue with compilation on Ubuntu 19.10
```
Bonzomatic/src/platform_x11/MIDI.cpp:4:10: fatal error: alsa/asoundlib.h: No such file or directory
    4 | #include <alsa/asoundlib.h>
```

It was solved by:
```
sudo apt install libasound2-dev
```

Cheers from Revision 2020 online party!

**Comment by Gargaj** [comment]
@PoroCYon

**Comment by PoroCYon** [comment]
That's normal. I'll update the docs.
