### ISSUE TITLE
Download and install

### ISSUE THREAD

**Issue by L4R5W** [Gargaj/Bonzomatic#140]
Hey guys!
I've got some problems with installing bonzomatic on my windows 10. Can someone give me some instructions for what software I need else? Cause if I just download the zip folder, there is no application that I can start. Pls help me.
Greetings Lars

**Comment by Gargaj** [comment]
Are you downloading the source or [one of the releases](https://github.com/Gargaj/Bonzomatic/releases)?

**Comment by L4R5W** [comment]
Yes I did.

**Comment by Gargaj** [comment]
You did which?

**Comment by L4R5W** [comment]
The one you upload 25 days ago. The last one

**Comment by havoc242** [comment]
Bonzomatic_W64_2020-05-09.zip ?

**Comment by friol** [comment]
@L4R5W make sure you downloaded the correct package, for example this one: https://github.com/Gargaj/Bonzomatic/releases/download/2020-05-09/Bonzomatic_W64_2020-05-09.zip , and then make sure your antivirus is not deleting the executables. They should be inside the .zip.

**Comment by sacredbanana** [comment]
How Git repos such as that stored in GitHub usually work is they most times only contain the files required to build the executable yourself. If people are kind enough to make things easy and provide their built executable, that is found in the Releases tab on the GitHub page for the project. Not all GitHub repos have this luxury though. Have fun with Bonzo!

**Comment by L4R5W** [comment]
Uuuh yes! Antivirus caused the problems..... Thx to you all! :)
