### ISSUE TITLE
postExit command not executed on Linux

### ISSUE THREAD

**Issue by thatguyjk** [Gargaj/Bonzomatic#158]
I am attempting to run a bash script on exit. To test to make sure it's working I have and echo statement that get printed before the copy command.

`echo "testing copy"
cp "$1" "~/shader_backups/shader-$(date +%s).glsl"
`

**Comment by PoroCYon** [comment]
are you sure?

https://github.com/Gargaj/Bonzomatic/blob/master/src/platform_x11/Misc.cpp#L33

**Comment by thatguyjk** [comment]
From my tests,  printing to the command line (without doing anything with the arguments) should still work as a valid script. Closing the program, either by ctrl+c on the command line or alt+f4 doesn't trigger anything. Am I missing something? I feel like I'm missing something 😕

**Comment by thatguyjk** [comment]
I'm  going to close this issue, for Linux you need to have the command as  `"postExitCmd": "./script_to_run.sh"`
