### ISSUE TITLE
How to forward user data between frames in Bonzomatic?

### ISSUE THREAD

**Issue by xintrea** [Gargaj/Bonzomatic#164]
Hi!

Does Bonsomatic have the ability to transfer user data (data arrays) between frames?

How can you write data, for example, to a texture, and read this data on the next frame?

**Comment by Gargaj** [comment]
With latest code, there is a texture that contains the contents of the frame you just rendered.

**Comment by xintrea** [comment]
> With latest code, there is a texture that contains the contents of the frame you just rendered.

I am interested in the transfer of user data (or user arrays). Is it possible?

**Comment by Gargaj** [comment]
You can use the previous frame data as an array; e.g. the top row of pixels in 1920x1080 will give you 1920x3 bytes worth of data that gets carried over to the next frame.

**Comment by xintrea** [comment]
This method show ugly random pixel at top row? And other shader procedure maybe write another data to this pixel and destroy this data?

**Comment by Gargaj** [comment]
You're the one writing the shader, so there's no "maybe".
