### ISSUE TITLE
Too darkness texture

### ISSUE THREAD

**Issue by xintrea** [Gargaj/Bonzomatic#165]
Hello!

I am try show one texture from *.png-file. Code is easy:
```
out vec4 FragColor;
                 
uniform float fGlobalTime;// in seconds
uniform vec2 v2Resolution;// viewport resolution (in pixels)
uniform float fFrameTime;// duration of the last frame, in seconds

uniform sampler2D textureBackground;

vec4 showBackground(vec2 uvPixelPosition)
{
    return texture(textureBackground, vec2(uvPixelPosition.x, -uvPixelPosition.y) );
}

void main(void)
{
    vec2 uv=vec2(gl_FragCoord.x/v2Resolution.x, gl_FragCoord.y/v2Resolution.y);
    FragColor=showBackground(uv);
}
```
The texture is show, but its colors very darkness. Compare screenshot:

http://i.piccy.info/i9/b29f16952714ffa142c075ef3fd8c13d/1629579290/338194/1431197/bonzomatic_compare.png

How to show texture with correct colors?

**Comment by Gargaj** [comment]
Probably loaded in as linear; try gamma correcting it:
`FragColor=pow(showBackground(uv),2.2);`

**Comment by xintrea** [comment]
> FragColor=pow(showBackground(uv),2.2);

Emmm.. Function pow() don't have prototype pow(vec4, float).

**Comment by xintrea** [comment]
Correct code is:
```
FragColor=pow(color, vec4(1/2.2));
```

**Comment by Gargaj** [comment]
Right, sorry, I was thinking HLSL :)
