### ISSUE TITLE
macOS: Bonzomatic.app requires Rosetta (2) to be installed?

### ISSUE THREAD

**Issue by artkiver** [Gargaj/Bonzomatic#176]
So the build instructions:

```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
cmake --build .
```

Function A-OK for me. So much so that I was thinking, "hey maybe I'll create a MacPort".

However the Bonzomatic.app bundle (whether built from source or using one of the releases) wants Rosetta (2) to be installed (this would only be prompted on an Apple Silicon Mac which did not already have Rosetta [2] installed).

Are there some dependencies which are architecture specific? Perhaps we can improve upon that?

Thank you!

For reference the system with which I was testing:
```
macOS 13.4.1 22F82 arm64
Xcode 14.3.1 14E300c
```

**Comment by julien** [comment]
Hey @artkiver,

I had the same issue and haven't taken the time to submit a pull request, but here's a patch you might want to try.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2f3209c..d40d4ae 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -50,7 +50,12 @@ if (APPLE OR WIN32)
   ############################################################################
   # MacOS
   if (APPLE)
-    set(CMAKE_OSX_ARCHITECTURES x86_64)
+    if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64")
+      set(CMAKE_OSX_ARCHITECTURES x86_64)
+    elseif (${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm64")
+      set(CMAKE_OSX_ARCHITECTURES arm64)
+    endif()
+
     set(CMAKE_FIND_FRAMEWORK LAST)
     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++14")
     set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
```

**Comment by artkiver** [comment]
> Hey @artkiver,
> 
> I had the same issue and haven't taken the time to submit a pull request, but here's a patch you might want to try.
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 2f3209c..d40d4ae 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -50,7 +50,12 @@ if (APPLE OR WIN32)
>    ############################################################################
>    # MacOS
>    if (APPLE)
> -    set(CMAKE_OSX_ARCHITECTURES x86_64)
> +    if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "x86_64")
> +      set(CMAKE_OSX_ARCHITECTURES x86_64)
> +    elseif (${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm64")
> +      set(CMAKE_OSX_ARCHITECTURES arm64)
> +    endif()
> +
>      set(CMAKE_FIND_FRAMEWORK LAST)
>      set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++14")
>      set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")
> ```

I tested this and it seems to have done the trick! No more prompt for Rosetta(2) to be installed!

I can prep and submit a PR if you prefer?

**Comment by artkiver** [comment]
Ah, nevermind! I see you already submitted a PR here!

https://github.com/Gargaj/Bonzomatic/pull/177

LGTM!

Thanks!

**Comment by artkiver** [comment]
Merge https://github.com/Gargaj/Bonzomatic/commit/84ed5e7911f5ab8f68fdc2ce40f9b2cfedc8a420 closes this issue.
