### ISSUE TITLE
Setting font path (on linux) is impossible

### ISSUE THREAD

**Issue by 22459** [Gargaj/Bonzomatic#39]
Setting the font path in json fails on:
https://github.com/Gargaj/Bonzomatic/blob/fdf9d1145c2a1489dc8aa4c579734e580bc93350/src/main.cpp#L159
Removing that line fixes it but I didn't look at the code enough to figure out whether that's a good thing.

**Comment by Gargaj** [comment]
Yeah that assert should probably move after the configuration stuff.
