### ISSUE TITLE
list of inputs available to shaders running in the program?

### ISSUE THREAD

**Issue by lukeoftheaura** [Gargaj/Bonzomatic#55]
Is it documented anywhere the list of (non-openGL standard) inputs that are available to shaders running within this program?

**Comment by Gargaj** [comment]
What inputs do you mean?

**Comment by lukeoftheaura** [comment]
input uniforms, like fGlobalTime and such (the ones not standard to GLSL)

**Comment by Gargaj** [comment]
They should be documented in the shader itself (e.g. https://github.com/Gargaj/Bonzomatic/blob/master/src/platform_glfw/Renderer.cpp#L120)

**Comment by lukeoftheaura** [comment]
Are those all the inputs you can have to a shader in this program? Is there no other uniforms you can use for an input?

**Comment by Gargaj** [comment]
There's the textures and the MIDI, but that's about it. My aim was to keep this is as simple as possible.
