### ISSUE TITLE
GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by Zash** [Gargaj/Bonzomatic#56]
Attempting to run on Debian 9.4. Appears to build fine, but when running:

```
$ ./Bonzomatic
OpenSetupDialog STUB
GLX: Failed to create context: GLXBadFBConfig
[GLFW] Window creation failed
Renderer::Open failed
```

**Comment by Gargaj** [comment]
@PoroCYon ^^^^

**Comment by PoroCYon** [comment]
This usually happens when the OpenGL version isn't supported. At least OpenGL 4.1 is required, can you give me the output of `glxinfo`?

**Comment by Zash** [comment]
[Output of `glxinfo`](https://gist.github.com/Zash/eaa5891da7c09fefdcd40ec5626a90aa).

**Comment by rgiot** [comment]
Unable to answer such question :(

**Comment by Gargaj** [comment]
No although a version check could be a good idea.

**Comment by Zash** [comment]
A line in the readme would be nice too.

**Comment by PoroCYon** [comment]
#57

**Comment by PoroCYon** [comment]
@Gargaj: close this now that #57 has been merged?
