### ISSUE TITLE
YouTube video in the README has been blocked for most countries

### ISSUE THREAD

**Issue by tanis2000** [Gargaj/Bonzomatic#62]
The YouTube video that is in the README has been blocked for most countries, apparently due to the copyright of the music. Could anyone get in touch with the party management and let them know and see if they can do anything to unlock it? Cheers!

**Comment by Gargaj** [comment]
That's a shame; I'll replace it but I kinda wanted the first one to be there.

**Comment by tanis2000** [comment]
@Gargaj indeed I'd like to watch it as well :-P
