### ISSUE TITLE
Segmentation fault under linux mint 

### ISSUE THREAD

**Issue by lamogui** [Gargaj/Bonzomatic#90]
Scenario:
 - Use linux mint latest version 
 - Download source
 - add all dependencies 
> sudo apt install cmake clang libx11-dev libxrandr-dev libxnerama-dev libxcursor-dev 
 - build using cmake and make
 - run 
 - crash after `MIDI::Open() failed, continuing anyway...`

Call stack using lldb (nullptr passed to strlen): 
> frame #0: 0x00007ffff602c5a1 libc.so.6`__strlen_avx2 at strlen-avx2.S:62

**Comment by lamogui** [comment]
Hum not reproduced on master. 
Maybe it's also related to the fact I installed libvulkan-dev because I saw it was missing with the master CMakeLists.txt ?

**Comment by Gargaj** [comment]
Is that the full call stack?
