### ISSUE TITLE
Drawing texture previews significantly slows down FFT updating on macOS

### ISSUE THREAD

**Issue by DanielOaks** [Gargaj/Bonzomatic#91]
Hey there! So I've been trying this out this on my fairly beefy Macbook, writing up some shaders. Noticed that when I have the code display open (and specifically, when I have the texture previews open on the right-hand side) the FFT variables seem to stop updating. I'm not sure whether it's an issue generally with the new mini_al stuff, or just for my specific set of hardware though (i7, 16GB RAM, Radeon Pro 460).

To see what I mean, I've got an example with a shader that updates things based on the FFT:
https://www.youtube.com/watch?v=oiPx3q0-_as

Commenting out [this function here](https://github.com/Gargaj/Bonzomatic/blob/master/src/main.cpp#L449) resolves the issue and makes the shader display properly while the texture preview sidebar is open:

```cpp
          Renderer::RenderQuad(
            Renderer::Vertex( x1, y1, 0xccFFFFFF, 0.0, 0.0 ),
            Renderer::Vertex( x2, y1, 0xccFFFFFF, 1.0, 0.0 ),
            Renderer::Vertex( x2, y2, 0xccFFFFFF, 1.0, 1.0 ),
            Renderer::Vertex( x1, y2, 0xccFFFFFF, 0.0, 1.0 )
          );
```

Example of running with this change:
https://www.youtube.com/watch?v=7OqKnOFWBro

The interesting thing is that on one of my more complex shaders, if I only draw with the 256x256 checker texture, the FFT does update, just more slowly than usual. On that same shader, if I draw one of the 1024x1024 shaders, the FFT doesn't update at all (or at least it's so slow it feels like it doesn't at all). Which makes me suspect that the size (and/or necessary scaling or something) of the textures factors into it.

Makes me think that rendering those textures to the screen is what's slowing it down juuust enough for the FFT updating to mess up. I've tried writing up a change to precalc texture previews but haven't managed to work out exactly how to do so yet (need to dig into using GLFW and such :P).

Little example GLSL shader that I've used for the above videos:
```glsl
#version 410 core

uniform sampler1D texFFT; // towards 0.0 is bass / lower freq, towards 1.0 is higher / treble freq
uniform sampler1D texFFTSmoothed; // this one has longer falloff and less harsh transients
uniform sampler1D texFFTIntegrated; // this is continually increasing

layout(location = 0) out vec4 out_color; // out_color must be written in order to see anything

void main(void)
{
  float r, g, b;

  r = sin(gl_FragCoord.x*0.04-texture(texFFTIntegrated, 0.2).r*2);
  g = sin(gl_FragCoord.x*0.04+1-texture(texFFTIntegrated, 0.2).r*2);
  b = sin(gl_FragCoord.x*0.04+2-texture(texFFTIntegrated, 0.2).r*2);

  out_color = vec4(r, g, b, 1);
}
```

Thanks for making this awesome tool! Been really fun to learn about GLSL using it. Please let me know if you're after any more information.

**Comment by Gargaj** [comment]
@alkama comments?

**Comment by Gargaj** [comment]
Also, does the framerate drop when the textures are drawn (i.e. if you have an effect that's time-based) or is it just the FFT?

**Comment by DanielOaks** [comment]
No framerate drop when it happens, only the FFT that slows to a crawl.

**Comment by Gargaj** [comment]
What I meant is whether effects that have a time parameter added slow down as well.

**Comment by DanielOaks** [comment]
Ah, nah effects based on the time parameter stay going the same speed, no slowdown on them.

**Comment by DanielOaks** [comment]
Had to remove the `const` from line 46 as well, but no changes after adding that line

**Comment by Gargaj** [comment]
¯\_(ツ)_/¯ I'll leave this to @alkama then, he can repro it.

**Comment by DanielOaks** [comment]
Definitely, thanks for the help so far! If I get anywhere with it I'll throw it in here

**Comment by alkama** [comment]
Apparently it's the whole FPS that drop bad when drawing those GUI textures...
There probably are some bad context switches. We might need to do those as special case like having same buffer and shader and binding them all using texture units like for the real shader.

Non accurate (but revealing) ms per frames shows:
0.6ms without the texture block
7ms while iterating textures but only drawing texture names
11ms with textures and their names

**Comment by alkama** [comment]
OK, so performance is shitty because of all the context switches...

But more importantly, this reveals a more architectural problem (if I understand correctly):
- the FFT is updated every frame, so integrated FFTs are fps-dependant! When using vsync you'll be at fixed FPS (unless shader is complex enough to miss sync). But with vsync disabled, you'll see what happens here.

We could either multithread FFT data aggregation, or only change FFT data at known fixed poll per seconds.

**Comment by alkama** [comment]
Yeah, maybe on PC with big GPU it has less impact and is less apparent :D Doesn't change the fact that integrated values in FFT are fps-dependant. So question is: should we fix it and make it independent or keep it as is (and maybe force vsync on mac so that there's no such big jump in values).

**Comment by cupe** [comment]
yeah, I'd probably go for the quick and easy scaling with deltatime forst to see if it fixes the thing. Doing the whole thing in a separate thread would be nice because it would have allow adding the current FFT to the integrated one more often than once every 1./60sec - IIRC, we currently lose some audio frames that don't contribute to the integral at all because the time step is too large.

**Comment by alkama** [comment]
@DanielOaks Ok, so along with that underlying problem (that still stands and that i'll fix eventually), it seems GLFW had some problems with 10.14 on respecting swap intervals (so vblank in our case).
It's been fixed in glfw3.3 and I just updated my branch with the "master" version of it.
I'll compile new zip file with the change along with new indentation feature :D 
It totally hides (but not really fixes) the problem on my machine.

**Comment by DanielOaks** [comment]
@alkama awesome, thanks very much for digging into it mate! Will def give it a shot on my end

**Comment by Gargaj** [comment]
Is this still an issue now that we've moved to 3.3?

**Comment by Gargaj** [comment]
@alkama @DanielOaks Is this still an issue now that we've moved to 3.3?

**Comment by alkama** [comment]
Not on my side :D I mean it's still framerate dependant but swap interval is respected so it's more predictible.

**Comment by Gargaj** [comment]
I was mostly asking about the framerate drop; the framerate dependency is a separate issue.
