### ISSUE TITLE
Bonzomatic for Windows now instantly crashes

### ISSUE THREAD

**Issue by sacredbanana** [Gargaj/Bonzomatic#94]
I don't know why, but Bonzomatic has suddenly stopped working entirely on Windows for me. I am using the latest version of the `master` branch. When I debug it I get this:

![image](https://user-images.githubusercontent.com/6903516/53809434-af928880-3f8f-11e9-9404-9c38d22961c5.png)

Could this be caused by a Windows update? I am in the Windows Insider program so I get early builds.

**Comment by sacredbanana** [comment]
Or maybe we need to update the GLFW library

**Comment by Gargaj** [comment]
What's the variable state there?

**Comment by sacredbanana** [comment]
The problem can be seen in the variable list in this pic. For some reason the GLFWmonitor can't be read from memory! What on Earth is going on?

![image](https://user-images.githubusercontent.com/6903516/54073627-9a399900-42c4-11e9-9d39-393c32a6a18f.png)

**Comment by sacredbanana** [comment]
OK I saw there's a new Nvidia driver released so I updated and it seems to be fine now.
