### ISSUE TITLE
Windows GLFW crash

### ISSUE THREAD

**Issue by fekga** [Gargaj/Bonzomatic#97]
I just downloaded the latest CMake, Visual Studio and Nvidia driver and Bonzomatic crashes for me.
I built the Release version with Debug info and the exception is thrown in the mini_al.h init function at this line: ```mal_zero_object(pDevice);```

Is there any workaround for this or some fix maybe?

**Comment by Gargaj** [comment]
"Latest Visual Studio" meaning 2019?

**Comment by fekga** [comment]
Yes. Is it not working with that one? Which one should I use?

**Comment by Gargaj** [comment]
We've had a bit of an issue with 2019 and we have no idea why; could be a compiler bug. Anything else above 2010 should work.

**Comment by fekga** [comment]
As I was debugging it there was a really strange thing happening. 
When the execution got to the `if (!mal__is_channel_map_valid(config.channelMap, config.channels)) {` part, it went into the if statement where it should have returned. Instead of returning the execution continued and got to the zero_object check where it got the exception.

**Comment by alkama** [comment]
Found  the bug, it's in mini_al.h

They use `ZeroMemory` instead of `SecureZeroMemory` which might lead to bad results on optimising compilers.

So changing line 3154 from
```
#define MAL_ZERO_MEMORY(p, sz) ZeroMemory((p), (sz))
```
to
```
#define MAL_ZERO_MEMORY(p, sz) SecureZeroMemory((p), (sz))
```
on VS2019 works.

**Comment by alkama** [comment]
Ok technically we could also read something from the struct once to force it not to be optimised away.
Or to allocate it on the heap.

Lets see what fits better, but at least you have a temporary fix that works for VS2019 and shouldn't hurt :D

**Comment by fekga** [comment]
Good job! I hope this gets fixed on either side :)

**Comment by alkama** [comment]
I referenced it here https://github.com/dr-soft/miniaudio/issues/58
I'll see if i can reproduce it with their example.
