### ISSUE TITLE
Shader crash in Bonzomatic (windows 10)

### ISSUE THREAD

**Issue by theotime** [Gargaj/Bonzomatic#99]
**Release**: Bonzomatic_W64_2019-03-26
**exe**: Bonzomatic_W64_GLFW.exe

Shader (attached to this ticket) produces crash at load on nvidia GTX 1060 (freeze on white screen on Intel HD5000).
When copy pasting this shader on a fresh bonzomatic session, it crash too.

[crashshader.txt](https://github.com/Gargaj/Bonzomatic/files/3100353/crashshader.txt)

Tell me if you need more information.
Thanks!

**Comment by Gargaj** [comment]
Looks to me that `for(;i<1.;i+.01){` never increments `i` (typo?) so it runs into an infinite loop?

**Comment by theotime** [comment]
Oh I totally miss that. I had several crash in different context during last week, and it was the only shader I kept, I did review this shader to see if it was mistake by me, but my tired eyes didn't catch that.

Sorry for this wrong issue.
